version: "3.9"
services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80 --reload
    ports:
      - 8000:80
    environment:
      - POKEMANTLE_POKEDEX=/data/pokedex.csv
      - POKEMANTLE_NAME_MAP=/data/name_map.csv
      - POKEMANTLE_OLD_SECRET=/data/old_secret.csv
    volumes:
      - ./data:/data
      - ./backend/app:/app/app
  frontend:
    build: ./frontend
    entrypoint: sh
    command: -c "npm install && npm run dev"
    ports:
      - 3000:3000
      - 50443:50443
    volumes:
      - ./frontend:/home/node/app
    environment:
      - NUXT_PUBLIC_API_CLIENT_BASE=http://localhost:8000
      - NUXT_PUBLIC_SPRITE_BASE=http://sprite:80
      - NUXT_API_SERVER_BASE=http://backend:80

  sprite:
    image: nginx:alpine
    ports:
      - 8001:80
    restart: unless-stopped
    volumes:
      - "./images/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./images/sprites/sprites/pokemon:/usr/share/nginx/html:ro"
