version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - 8000:80
    environment:
      - POKEMANTLE_POKEDEX=/data/pokedex.csv
      - POKEMANTLE_NAME_MAP=/data/name_map.csv
      - POKEMANTLE_PRODUCTION=True
    volumes:
      - ./data:/data
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    environment:
      - POKEMANTLE_PRODUCTION=True
