version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - 8000:80
    environment:
      - POKEMANTLE_POKEDEX=/data/pokedex.csv
      - POKEMANTLE_NAME_MAP=/data/name_map.csv
      - POKEMANTLE_OLD_SECRET=/data/old_secret.csv
      - POKEMANTLE_PRODUCTION=True
      - POKEMANTLE_CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./data:/data
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    environment:
      - NUXT_PUBLIC_API_CLIENT_BASE=http://localhost:8000
      - NUXT_PUBLIC_SPRITE_BASE=http://localhost:8001
      - NUXT_API_SERVER_BASE=http://backend:80
      - POKEMANTLE_PRODUCTION=True

  sprite:
    image: nginx:alpine
    ports:
      - 8001:80
    restart: unless-stopped
    volumes:
      - "./images/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./images/sprites/sprites/pokemon:/usr/share/nginx/html:ro"
